config/routes.rb
MembershipSite::Application.routes.draw do

	mount StripeEvent::Engine => '/stripe'

  get "content/silver"

  get "content/gold"

  get "content/platinum"


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users


  resources :incidents do
    resources :feelings
    resources :thoughts do
      resources :distortions
    end
  end




end

app/models/feeling.rb
class Feeling
	include Mongoid::Document
	#include Mongoid::ActsAsList

	field :name, type: String
	field :intensityBefore, type: Integer
	field :intensityAfter, type: Integer

	embedded_in :incident, :inverse_of => :feelings

end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController
  #before_filter :authenticate_user!
	
	def create
		@incident = Incident.find(params[:incident_id])
		@feeling = @incident.feelings.create!(params[:feeling])
    
    if @feeling.save
      flash[:notice] = "New feeling Added"
    else
      flash[:alert] = "Your feeling might have some errors, please check and try again."
    end

    respond_to do |format|
      format.js
    end
	end

  def edit
    @incident = Incident.find(params[:incident_id])
    @feeling = @incident.feelings.find(params[:id])
  end

  def update
    @incident = Incident.find(params[:incident_id])
    @feeling = @incident.feelings.find(params[:id])
    respond_to do |format|
      if @feeling.update_attributes(params[:feeling])
          format.html { redirect_to @incident, notice: 'Your incident was updated.' }
      else
        format.html {render action: "edit"}
      end
    end
  end

  def sort
    @feelings = Incident.feeling
    @feelings.each do |feeling|
      p feeling.position = params['feeling'].index(feeling.id.to_s) +1
      feeling.save
    end

    render :nothing => true
  end

  def destroy
    @incident = Incident.find(params[:incident_id])
    @feeling = @incident.feelings.find(params[:id])
    @feeling.destroy

    respond_to do |format|
     format.js
    end
  end

end

app/helpers/feelings_helper.rb
module FeelingsHelper
end

app/views/feelings/_feeling.html.erb
<%= content_tag_for(:li, feeling, :class => "feelingList") do %>

	<div>
		<div>

			<span class="btn-group pull-right" >
		
			<%= link_to edit_incident_feeling_path(@incident, feeling), :class => "editFeeling" do %><i class="icon-edit"></i><%end%>
		    <%= link_to [@incident, feeling], :method => :delete, :class => "deleteFeeling", :remote => true do  %>
		    <i class="icon-trash"></i>
		    <%end%>
			
			</span>

		</div>
	</div>


	<div id="feelingContent" class="feelingContent">
		<%= feeling.name %>
		<%= feeling.intensityBefore %>
		<%= feeling.intensityAfter %>
	</div>


<% end %>

app/views/feelings/_feeling_list.html.erb
<li><a href="#feeling_<%= feeling.id %>"><%= feeling.name %></a></li>

app/views/feelings/create.js.erb
	$("#feelingModal").modal('hide');
	$("#feelings-list").append("<%= escape_javascript(render(@feeling)) %>");
	$("#feelingsTC").append("<%= escape_javascript(render(:partial => 'feelings/feeling_list', :locals =>{:feeling => @feeling})) %>");
	$('#new_feeling').each (function(){
  		this.reset();
	});

app/views/feelings/destroy.js.erb
$('#feeling_<%= @feeling.id %>').fadeOut()