config/routes.rb
MembershipSite::Application.routes.draw do

	mount StripeEvent::Engine => '/stripe'

  get "content/silver"

  get "content/gold"

  get "content/platinum"


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users


  resources :incidents do
    resources :feelings
    resources :thoughts do
      resources :distortions
    end
  end




end

app/models/incident.rb
class Incident
  include Mongoid::Document
  include Mongoid::Timestamps
  #include Mongoid::Paranoia  # so that docs are not actually trashed 

  field :description, type: String

  
  embeds_many :feelings, cascade_callbacks: true
  embeds_many :thoughts
  
	accepts_nested_attributes_for :feelings , :autosave => true
	accepts_nested_attributes_for :thoughts, :autosave => true
  

  #field :_id, type: String, default: ->{ name.to_s.parameterize } # in case you want to change how Mongo Object IDs are assigned

#  attr_accessible :description, :feelings, :thoughts

  validates_presence_of :description




end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @incidents }
    end
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
    @incident = Incident.find(params[:id])
    @feelings = @incident.feelings.all
    @thoughts = @incident.thoughts.all
    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @incident }
    # end
  end

  # GET /incidents/new
  # GET /incidents/new.json
  def new
    @incident = Incident.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @incident }
    end
  end

  # GET /incidents/1/edit
  def edit
    @incident = Incident.find(params[:id])
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(params[:incident])

    respond_to do |format|
      if @incident.save
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render json: @incident, status: :created, location: @incident }
      else
        format.html { render action: "new" }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /incidents/1
  # PUT /incidents/1.json
  def update
    @incident = Incident.find(params[:id])

    respond_to do |format|
      if @incident.update_attributes(params[:incident])
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident = Incident.find(params[:id])
    @incident.destroy

    respond_to do |format|
      format.html { redirect_to incidents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_distortions.html.erb
<div>

	<h3>For each thought, what distortions do you notice?</h3>
	<ol>
	<% @incident.thoughts.each do |thought| %>
	<li><%= thought.thought %></li>
		<%= simple_form_for [@incident, thought, Distortion.new], :html => {:class => "form-vertical"},:remote => true do |f| %>
			<%= f.input :name %>
			<div class="btn-group">
				<span id="closeDistortion" class="btn">Cancel</span><%= f.button :submit, :id => "createDistortion" %>
			</div>
		<%end%>
	<%end%>
	</ol>
</div>

app/views/incidents/_feelings.html.erb
<div>

	<h>What are you feeling?</h3>

	<%= simple_form_for [@incident, Feeling.new], :html => {:class => "form-vertical"},:remote => true do |f| %>
		<%= f.input :name %>
		<%= f.input :intensityBefore %>
		<div class="btn-group">
			<span id="closeFeeling" class="btn">Cancel</span><%= f.button :submit, :id => "createFeeling" %>
		</div>
	<%end%>
</div>

app/views/incidents/_form.html.erb
<%= simple_form_for @incident do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>



  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/incidents/_intensity_after.html.erb
<div>

	<h>Now that you've analyzed your thinking, how do you feel?</h3>

	<% @incident.feelings.each do |feeling| %>
		<li><%= feeling.name %></li>
		<%= simple_form_for [@incident, feeling], :html => {:class => "form-vertical"},:remote => true do |f| %>
			<%= f.input :intensityAfter %>
			<div class="btn-group">
				<span id="closeFeeling" class="btn">Cancel</span><%= f.button :submit, :id => "createFeeling" %>
			</div>
		<%end%>
	<%end%>
</div>


		<!--

		- grab collection of @incident.feelings
		- for each feeling, indicate new value for intensityAfter
		- append each new value 1) to list here, and 2) in main incident

		-->

app/views/incidents/_rational_thoughts.html.erb
<div>

	<% @incident.thoughts.each do |thought| %>
		<li><%= thought.thought %></li>
		<%= simple_form_for [@incident, thought], :html => {:class => "form-vertical"},:remote => true do |f| %>
			<%= f.input :rationalThought %>
			<div class="btn-group">
				<span id="closeRationalThought" class="btn">Cancel</span><%= f.button :submit, :id => "createRationalThought" %>
			</div>
		<%end%>
	<%end%>
</div>




		<!--

		- grab collection of @incident.thoughts
		- for each thought, append a form with field to enter rational version
		- append each new rational version 1) to each thought here, and 2) to each thought in main incident

		-->

app/views/incidents/_thoughts.html.erb
<div>

	<h>What did you think?</h3>

	<%= simple_form_for [@incident, Thought.new], :html => {:class => "form-vertical"},:remote => true do |f| %>
		<%= f.input :thought %>
		<div class="btn-group">
			<span id="closeThought" class="btn">Cancel</span><%= f.button :submit, :id => "createThought" %>
		</div>
	<%end%>

</div>

app/views/incidents/edit.html.erb
<h1>Editing incident</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<h1>Listing incidents</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Feelings</th>
    <th></th>
    <th></th>
  </tr>

<% @incidents.each do |incident| %>
  <tr>
    <td><%= incident.description %></td>
    <td><%= link_to 'Show', incident %></td>
    <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
    <td><%= link_to 'Destroy', incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Incident', new_incident_path %>

app/views/incidents/new.html.erb
<h1>New incident</h1>

<%= render 'form' %>

<%= link_to 'Back', incidents_path %>

app/views/incidents/show.html.erb
<div class="row">
	<div class="span12">
		<div class="incident-description">
			<h3>Incident Report</h3>
			<p>
			  <h4>Description of the incident:</h4>
			  <%= @incident.description %>
			</p>
		</div>
	</div>
</div>
<hr>
<div class="row">
	<div id="wizard" class="span12">
		<p>
			<h5>CBT Wizard</h5>
			Please follow the wizard below and provide additional detail about the incident
		</p>
		<!--  Steps for the CBT wizard:
					1.  Feelings: names & intensityBefore
					2.  Thoughts
					3.  Distortions forEach thought
					4.  rationalThought for each thought
					5.  intensityAfter forEach feeling in feelings
				
		-->
		<div class="tabbable">
			<ul id="wizard-nav" class="nav nav-tabs" style="margin-bottom:0;padding-bottom:0">
					<li><a href="#step1"class="active" data-toggle="tab">Step 1</a></li>
					<li><a href="#step2"class="" data-toggle="tab">Step 2</a></li>
					<li><a href="#step3"class="" data-toggle="tab">Step 3</a></li>
					<li><a href="#step4"class="" data-toggle="tab">Step 4</a></li>
					<li><a href="#step5"class="" data-toggle="tab">Step 5</a></li>
					<li><a href="#summary"class="" data-toggle="tab">Summary</a></li>
			</ul>
		<div class="tab-content wizard-steps" style="min-height:300px;padding:10px;background-color:#fff;">
			<div id="step1" class="tab-pane active">
				<div>
					<h5>Add Feelings</h5>
					<p>List each different feeling and and how intensely you are experiencing it, on a scale of 1 to 10</p>
					<div id="addFeeling" class="btn"><i class="icon-plus"></i> Add a feeling</div>
					<div id="newFeelingPartial" style="display:none"><%= render 'feelings' %></div>
					<ul id="feelingsTC" class="nav navlist">
						<% @incident.feelings.each do |feeling| %>
						<li class="feeling">
							<a href="#feeling_<%=feeling.id %>"><%= feeling.name %></a>
						</li>
						<%end%>
					</ul>
				</div>
			</div>

			<div id="step2" class="tab-pane">
				<div>
					<h5>Add Thoughts</h5>
					<p>List all the thoughts you had about this incident.</p>
					<div id="addThought" class="btn"><i class="icon-plus"></i> Add a thought</div>
					<div id="newThoughtPartial" style="display:none"><%= render 'thoughts' %></div>
					<ul id="thoughtsTC" class="nav navlist">
						<% @incident.thoughts.each do |thought| %>
							<li class="thought"><a href="#thought_<%=thought.id %>"><%= thought.thought %></a></li>
						<%end%>
					</ul>
				</div>
			</div>

			<div id="step3" class="tab-pane">
				<h5>Add Distortions</h5>
				<p>For each thought you listed, list all the distortions apparrent in that thought.</p>
				<div id="newDistortionsPartial" style="display:"><%= render 'distortions' %></div>
			</div>

			<div id="step4" class="tab-pane">
				<h5>Add Rational Alternatives</h5>
				<p>For each thought, provide a more rational alternative.</p>
				<div id="newRationalThoughtPartial" style="display:"><%= render 'rational_thoughts' %></div>
			</div>

			<div id="step5" class="tab-pane">
				<h5>Re-assess Feelings</h5>
				<p>Now go back to each feeling you listed and indicate how you intensely you feel it now.</p>
				<div id="newIntensityAfterPartial" style="display:"><%= render 'intensity_after' %></div>
			</div>

			<div id="summary" class="tab-pane">
				<div class="row">
					<div id="incident-show">	
						<div class="offset2 span3">
							<h5>Feelings</h5>
							<ul id="feelingsTC" class="nav navlist">
								<% @incident.feelings.each do |feeling| %>
									<li class="feeling"><a href="#feeling_<%=feeling.id %>"><%= feeling.name %></a></li>
								<%end%>
							</ul>
						</div>
						<div class="span3">
							<h5>Thoughts</h5>
							<ul id="thoughtsTC" class="nav navlist">
								<% @incident.thoughts.each do |thought| %>
									<li class="thought"><a href="#thought_<%=thought.id %>"><%= thought.thought %></a></li>
									<ul id="distortionsTC">
									<% thought.distortions.each do |distortion| %>
										<li><%= distortion.name %></li>
									<% end %>
									</ul>
								<%end%>
							</ul>
						</div>		
					</div><!-- /incident-show -->
				</div>
			</div>
		</div>


		<script>
			//show the first step on page load
		  $(function () {
		    $('#wizard-nav a:first').tab('show');
		  })
		</script>




		</div><!-- /wizard-->
	</div><!-- /row -->
</div>
<hr>


<div class="row">
	<div class="span12">
		<div>
			<%= link_to 'Edit', edit_incident_path(@incident) %> |
			<%= link_to 'Back', incidents_path %>
		</div>
	</div>
</div>