config/routes.rb
MembershipSite::Application.routes.draw do

	mount StripeEvent::Engine => '/stripe'

  get "content/silver"

  get "content/gold"

  get "content/platinum"


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users


  resources :incidents do
    resources :feelings
    resources :thoughts do
      resources :distortions
    end
  end




end

app/models/thought.rb
class Thought 
	include Mongoid::Document

	field :thought, type: String
	field :distortions, type: Array
	field :rationalThought, type: String
	attr_accessible :thought, :distortions, :rationalThought
	
	embedded_in :incident, :inverse_of => :thoughts
	embeds_many :distortions

	accepts_nested_attributes_for :distortions, :autosave => true

	
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  #before_filter :authenticate_user!
	
	def create
		@incident = Incident.find(params[:incident_id])
		@thought = @incident.thoughts.create!(params[:thought])
    
    if @thought.save
      flash[:notice] = "New thought Added"
    else
      flash[:alert] = "Your thought might have some errors, please check and try again."
    end

    respond_to do |format|
      format.js
    end
	end

  def edit
    @incident = Incident.find(params[:incident_id])
    @thought = @incident.thoughts.find(params[:id])
  end

  def update
    @incident = Incident.find(params[:incident_id])
    @thought = @incident.thoughts.find(params[:id])
    respond_to do |format|
      if @thought.update_attributes(params[:thought])
          format.html { redirect_to @incident, notice: 'Your incident was updated.' }
      else
        format.html {render action: "edit"}
      end
    end
  end

  def sort
    @thoughts = Incident.thought
    @thoughts.each do |thought|
      p thought.position = params['thought'].index(thought.id.to_s) +1
      thought.save
    end

    render :nothing => true
  end

  def destroy
    @incident = Incident.find(params[:incident_id])
    @thought = @incident.thoughts.find(params[:id])
    @thought.destroy

    respond_to do |format|
     format.js
    end
  end

end

app/views/thoughts/_thought.html.erb
<%= content_tag_for(:li, thought, :class => "thoughtList") do %>

	<div class="row">
		<div>

			<div class="moveThought pull-left"><i class="icon-move"></i></div>

			<span class="btn-group pull-right" >
			
			<%= link_to edit_incident_thought_path(@incident, thought), :class => "editThought" do %><i class="icon-edit"></i><%end%>
		    <%= link_to [@incident, thought], :method => :delete, :class => "deleteThought", :remote => true do  %>
		    <i class="icon-trash"></i>
		    <%end%>
			
			</span>

		</div>
	</div>


	<div id="thoughtContent" class="well thoughtContent">
		<h5> <%= thought.thought %></h5>
	</div>


<% end %>

app/views/thoughts/_thought_list.html.erb
<li><a href="#thought_<%= thought.id %>"><%= thought.thought %></a></li>

app/views/thoughts/create.js.erb
	$("#thoughtModal").modal('hide');
	$("#thoughts").append("<%= escape_javascript(render(@thought)) %>");
	$("#thoughtsTC").append("<%= escape_javascript(render(:partial => 'thoughts/thought_list', :locals =>{:thought => @thought})) %>");

	$('#new_thought').each (function(){
  		this.reset();
	});

app/views/thoughts/destroy.js.erb
$('#thought_<%= @thought.id %>').fadeOut()